# Generated by Django 4.2.2 on 2023-12-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_data',
            fields=[
                ('identity', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mno', models.IntegerField(max_length=12)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='pp')),
                ('address', models.TextField()),
                ('Biodata', models.TextField(default='Nothing to say')),
            ],
        ),
    ]
